### ISSUE TITLE
[Bug]: plot-sv-calls.R error

### ISSUE THREAD

**Issue by weber8thomas** [friendsofstrandseq/mosaicatcher-pipeline#6]
### Contact Details

thomas.weber@embl.de

### What happened?

Error when processing HGSVC pooling sample (HGVSCxPool2) on chr19

##

### Mosaicatcher-pipeline Version

1.5.1 (Default)

### Command used

```shell
snakemake --cores 10 --config mode=mosaiclassifier plot=True input_bam_location=/g/korbel2/weber/MosaiCatcher_files/POOLING/POOLING_POOL2/ output_location=/g/korbel2/weber/MosaiCatcher_output/POOLING/TEST_POOL2_CHR21/ window=200000 containerized=True chromosomes="[chr21]"  --use-singularity --singularity-args "-B /g:/g" --latency-wait 60 --use-conda -p
```

### How did you run the pipeline?

Conda + Singularity

### What did you use to run the pipeline? (local execution, HPC, cloud)

Local execution

### Pipeline configuration file

```YAML
#######################################
#   MOSAICATCHER CONFIGURATION FILE.  #
#######################################

mail: ""

#######################################
## Command-line options
#######################################

### Modes ["count", "segmentation", "mosaiclassifier"]
mode: "mosaiclassifier"
### Plot enabled [True] or disabled [False]
plot: False
### Enable / Disable comparison for each BAM file between folder name & SM tag
check_sm_tag: True
### Enable / Disable download of BAM examples (RPE-BM510)
dl_bam_example: False
### Enable / Disable download of external files (1000G SNV & Fasta ref genome)
dl_external_files: False

## Input BAM location
input_bam_location: ".tests/data/"
## Output location
output_location: ".tests/output/"

# External files
## 1000G SNV sites to genotype : https://sandbox.zenodo.org/record/1060653/files/ALL.chr1-22plusX_GRCh38_sites.20170504.renamedCHR.vcf.gz
snv_sites_to_genotype: sandbox.zenodo.org/record/1074721/files/ALL.chr1-22plusX_GRCh38_sites.20170504.renamedCHR.vcf.gz

# Reference genome : https://sandbox.zenodo.org/record/1060653/files/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
reference: sandbox.zenodo.org/record/1074721/files/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna

# Chromosomes list to process
chromosomes:
  - chr1
  - chr2
  - chr3
  - chr4
  - chr5
  - chr6
  - chr7
  - chr8
  - chr9
  - chr10
  - chr11
  - chr12
  - chr13
  - chr14
  - chr15
  - chr16
  - chr17
  - chr18
  - chr19
  - chr20
  - chr21
  - chr22
  - chrX

##############################
# Advanced configuration.  #
##############################

# Enable conda & singularity usage
use-conda: True
use-singularity: True
containerized: False
singularity-args: "-B /g:/g"
latency-wait: 60

# Default conda frontend
conda-frontend: "conda"

# Print shell commands
printshellcmds: True

# External static data
# R Ref
R_reference: "BSgenome.Hsapiens.UCSC.hg38"
# SegDups file
segdups: "workflow/data/segdups/segDups_hg38_UCSCtrack.bed.gz"

# Exclude cells
exclude_list: []

# Strandphaser
git_commit_strandphaser: "69c9fb4"
git_repo_strandphaser: "https://github.com/daewoooo/StrandPhaseR"
paired_end: True

# CHECKME : Parameters optimization ?
# PARAMETERS

## WINDOW
window: 100000

## METHODS
methods:
  - "simpleCalls_llr4_poppriorsTRUE_haplotagsTRUE_gtcutoff0_regfactor6_filterFALSE"
  - "simpleCalls_llr4_poppriorsTRUE_haplotagsFALSE_gtcutoff0.05_regfactor6_filterTRUE"

llr: 4
poppriors: TRUE
haplotags:
  - TRUE
  - FALSE
gtcutoff:
  - 0
  - 0.05
regfactor: 6
filter:
  - TRUE
  - FALSE

## BPDENS
### JOINT SEG
min_diff_jointseg: 0.1
### SINGLE SEG
min_diff_singleseg: 0.5
### SCE CUTOFF
additional_sce_cutoff: 20000000
### SCE MIN DISTANCE
sce_min_distance: 500000
```

### Relevant log output

```shell
* Reading count data /g/korbel2/weber/MosaiCatcher_output/POOLING/TEST_POOL2/counts/HGSVCxpool2/HGSVCxpool2.txt.gz...
Taking input= as a system command ('zcat /g/korbel2/weber/MosaiCatcher_output/POOLING/TEST_POOL2/counts/HGSVCxpool2/HGSVCxpool2.txt.gz') and a variable has been used in the expression passed to `input=`. Please use fread(cmd=...). There is a security concern if you are creating an app, and the app could have a malicious user, and the app is not running in a secure environment; e.g. the app is running as root. Please read item 5 in the NEWS file for v1.11.6 for more information and for the option to suppress this message.
 * Reading SV calls from /g/korbel2/weber/MosaiCatcher_output/POOLING/TEST_POOL2/mosaiclassifier/sv_calls/HGSVCxpool2/simpleCalls_llr4_poppriorsTRUE_haplotagsFALSE_gtcutoff0.05_regfactor6_filterTRUE.tsv...
 * Reading segmentation file from /g/korbel2/weber/MosaiCatcher_output/POOLING/TEST_POOL2/segmentation/HGSVCxpool2/Selection_jointseg.txt...
Error in `[.data.table`(seg, , `:=`(start = bins[from + N]$start, end = bins[to +  :
  Supplied 1072 items to be assigned to 1073 items of column 'end'. If you wish to 'recycle' the RHS please use rep() to make this intent clear to readers of your code.
Calls: [ -> [.data.table
In addition: Warning message:
In as.data.table.list(jval, .named = NULL) :
  Item 2 has 22 rows but longest item has 23; recycled with remainder.
```
